# Generated by Django 3.0.8 on 2020-08-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_direct', '0004__profile_tone_2_many'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
