# Generated by Django 3.0.8 on 2020-08-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_direct', '0006_add_fk_to_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='statement',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
