# Generated by Django 3.0.8 on 2020-08-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_direct', '0007_add_fields_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('event_organizer', 'Event Organizer'), ('artist', 'Artist')], default='event_organizer', max_length=24),
        ),
    ]
