# Generated by Django 3.0.8 on 2020-07-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_direct', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='f_name',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.CharField(blank=True, choices=[('Solo', 'Solo'), ('Chamber', 'Chamber'), ('Musical Theater', 'Musical_Theater')], default='Solo', max_length=24),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instrument',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='profile',
            name='l_name',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('CN', 'Canada'), ('EU', 'Europe')], default='US', max_length=2),
        ),
    ]
